image: "rust:latest"

check:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo check --verbose --package graphical_engine_library

build:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo build --verbose --package graphical_engine_library

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --verbose --no-default-features --no-fail-fast --package graphical_engine_library
