name: BitBucket Mirror

on:
  push:
    branches: ["**"]

jobs:
  bitbucket_mirror:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - run: git fetch --unshallow origin
      - run: git fetch --prune --all
      - run: git push --prune https://Sakul-Flee:$BITBUCKET_TOKEN@bitbucket.org/rust-multiplatform/base-project-template.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/*
        env:
          BITBUCKET_TOKEN: ${{ secrets.BITBUCKET_TOKEN }}
