name: Graphical Engine Library

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  graphical_engine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache target/
        id: target-cache
        uses: actions/cache@v3
        with:
          path: target
          key: library-target

      - name: Install GCC and dependencies
        run: sudo apt-get install -y build-essential gcc gcc-multilib

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

      - name: Install target x86_64-unknown-linux-gnu
        run: rustup target add x86_64-unknown-linux-gnu

      - name: Check
        run: cargo check --verbose --package graphical_engine --target x86_64-unknown-linux-gnu
      - name: Build (Debug)
        run: cargo build --verbose --package graphical_engine --target x86_64-unknown-linux-gnu
      - name: Build (Release)
        run: cargo build --verbose --package graphical_engine --target x86_64-unknown-linux-gnu --release
      - name: Run Tests (Debug)
        run: cargo test --verbose --package graphical_engine --no-default-features --no-fail-fast --target x86_64-unknown-linux-gnu
        continue-on-error: true
      - name: Run Tests (Release)
        run: cargo test --verbose --package graphical_engine --no-default-features --no-fail-fast --target x86_64-unknown-linux-gnu --release
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: "graphical_engine"
          path: |
            target/debug/libgraphical_engine.a
            target/debug/libgraphical_engine.d
            target/debug/libgraphical_engine.rlib
            target/debug/libgraphical_engine.so
            target/release/libgraphical_engine.a
            target/release/libgraphical_engine.d
            target/release/libgraphical_engine.rlib
            target/release/libgraphical_engine.so
          if-no-files-found: error
