name: Compute Engine Library

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  platform_linux:
    strategy:
      matrix:
        os: [ubuntu-latest]
        target: [x86_64-unknown-linux-gnu]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Cache target/
        id: target-cache
        uses: actions/cache@v3
        with:
          path: target
          key: library-${{ runner.os }}-${{ matrix.target }}-target

      - name: Install GCC and dependencies
        run: sudo apt-get install -y build-essential gcc gcc-multilib

      - name: Install Rust
        run: curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable --profile minimal -y

      - name: Install target ${{ matrix.target }}
        run: rustup target add ${{ matrix.target }}

      - name: Check
        run: cargo check --verbose --package compute_engine_library --target ${{ matrix.target }}
      - name: Build (Debug)
        run: cargo build --verbose --package compute_engine_library --target ${{ matrix.target }}
      - name: Build (Release)
        run: cargo build --verbose --package compute_engine_library --target ${{ matrix.target }} --release
      - name: Run Tests (Debug)
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }} # Testing can only be done on the host architecture. It should work across all architectures though!
        run: cargo test --verbose --package compute_engine_library --no-default-features --no-fail-fast --target ${{ matrix.target }}
        continue-on-error: true
      - name: Run Tests (Release)
        if: ${{ matrix.target == 'x86_64-unknown-linux-gnu' }} # Testing can only be done on the host architecture. It should work across all architectures though!
        run: cargo test --verbose --package compute_engine_library --no-default-features --no-fail-fast --target ${{ matrix.target }} --release
        continue-on-error: true

      - uses: actions/upload-artifact@v3
        with:
          name: "compute_engine_library_debug_${{ matrix.target }}"
          path: target/${{ matrix.target }}/debug/compute_engine_library
          if-no-files-found: error
      - uses: actions/upload-artifact@v3
        with:
          name: "compute_engine_library_release_${{ matrix.target }}"
          path: target/${{ matrix.target }}/release/compute_engine_library
          if-no-files-found: error
